"""

    This UnitTest was entirely generated by an AI

"""

import unittest
import sys
import os

# Add the code directory to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'code'))

from dice import validate_probabilities, generate_biased_rolls, process_request


class TestValidateProbabilities(unittest.TestCase):
    """Tests for the validate_probabilities function."""

    # --- Probabilities must sum exactly to 1.0 ---

    def test_valid_probabilities_sum_to_1(self):
        """Valid probabilities that sum to 1.0 should pass."""
        probs = [0.1, 0.2, 0.3, 0.1, 0.2, 0.1]
        is_valid, error = validate_probabilities(probs)
        self.assertTrue(is_valid)
        self.assertIsNone(error)

    def test_uniform_probabilities(self):
        """Uniform distribution (all 1/6) should pass."""
        probs = [1/6] * 6
        is_valid, error = validate_probabilities(probs)
        self.assertTrue(is_valid)
        self.assertIsNone(error)

    def test_probabilities_sum_less_than_1(self):
        """Probabilities summing to less than 1.0 should fail."""
        probs = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]  # sum = 0.6
        is_valid, error = validate_probabilities(probs)
        self.assertFalse(is_valid)
        self.assertIn("sum to 1.0", error)

    def test_probabilities_sum_greater_than_1(self):
        """Probabilities summing to more than 1.0 should fail."""
        probs = [0.3, 0.3, 0.3, 0.3, 0.3, 0.3]  # sum = 1.8
        is_valid, error = validate_probabilities(probs)
        self.assertFalse(is_valid)
        self.assertIn("sum to 1.0", error)

    # --- Must contain only numeric values ---

    def test_non_numeric_string_value(self):
        """String values in probabilities should fail."""
        probs = [0.1, "0.2", 0.3, 0.1, 0.2, 0.1]
        is_valid, error = validate_probabilities(probs)
        self.assertFalse(is_valid)
        self.assertIn("not numeric", error)

    def test_non_numeric_none_value(self):
        """None values in probabilities should fail."""
        probs = [0.1, None, 0.3, 0.1, 0.2, 0.1]
        is_valid, error = validate_probabilities(probs)
        self.assertFalse(is_valid)
        self.assertIn("not numeric", error)

    def test_non_numeric_list_value(self):
        """Nested list values in probabilities should fail."""
        probs = [0.1, [0.2], 0.3, 0.1, 0.2, 0.1]
        is_valid, error = validate_probabilities(probs)
        self.assertFalse(is_valid)
        self.assertIn("not numeric", error)

    # --- Do not contain negative numbers ---

    def test_negative_probability(self):
        """Negative probability values should fail."""
        probs = [-0.1, 0.3, 0.3, 0.1, 0.2, 0.2]
        is_valid, error = validate_probabilities(probs)
        self.assertFalse(is_valid)
        self.assertIn("negative", error)

    # --- Must include exactly six entries ---

    def test_too_few_entries(self):
        """Fewer than 6 entries should fail."""
        probs = [0.2, 0.3, 0.5]
        is_valid, error = validate_probabilities(probs)
        self.assertFalse(is_valid)
        self.assertIn("exactly 6", error)

    def test_too_many_entries(self):
        """More than 6 entries should fail."""
        probs = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.3]
        is_valid, error = validate_probabilities(probs)
        self.assertFalse(is_valid)
        self.assertIn("exactly 6", error)

    def test_empty_list(self):
        """Empty list should fail."""
        is_valid, error = validate_probabilities([])
        self.assertFalse(is_valid)
        self.assertIn("exactly 6", error)

    # --- Must be a list ---

    def test_not_a_list(self):
        """Non-list input should fail."""
        is_valid, error = validate_probabilities("not a list")
        self.assertFalse(is_valid)
        self.assertIn("must be a list", error)

    def test_tuple_input(self):
        """Tuple input should fail (must be a list)."""
        is_valid, error = validate_probabilities((0.1, 0.2, 0.3, 0.1, 0.2, 0.1))
        self.assertFalse(is_valid)
        self.assertIn("must be a list", error)

    # --- Edge cases ---

    def test_all_zero_except_one(self):
        """All probability on one face should pass."""
        probs = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        is_valid, error = validate_probabilities(probs)
        self.assertTrue(is_valid)
        self.assertIsNone(error)

    def test_integer_probabilities(self):
        """Integer values that sum to 1 should pass."""
        probs = [1, 0, 0, 0, 0, 0]
        is_valid, error = validate_probabilities(probs)
        self.assertTrue(is_valid)
        self.assertIsNone(error)


class TestGenerateBiasedRolls(unittest.TestCase):
    """Tests for the generate_biased_rolls function."""

    # --- Produces only values between 1 and 6 ---

    def test_all_values_in_range(self):
        """All generated values must be between 1 and 6."""
        probs = [0.1, 0.2, 0.3, 0.1, 0.2, 0.1]
        results = generate_biased_rolls(probs, 1000)
        for val in results:
            self.assertIn(val, [1, 2, 3, 4, 5, 6])

    def test_correct_count(self):
        """Should generate the exact number of rolls requested."""
        probs = [1/6] * 6
        results = generate_biased_rolls(probs, 50)
        self.assertEqual(len(results), 50)

    def test_single_roll(self):
        """Should work for a single roll."""
        probs = [1/6] * 6
        results = generate_biased_rolls(probs, 1)
        self.assertEqual(len(results), 1)
        self.assertIn(results[0], [1, 2, 3, 4, 5, 6])

    # --- Respects the defined probability distribution (statistical verification) ---

    def test_distribution_heavily_biased(self):
        """When all probability is on face 1, only face 1 should appear."""
        probs = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        results = generate_biased_rolls(probs, 100)
        for val in results:
            self.assertEqual(val, 1)

    def test_distribution_statistical_verification(self):
        """
        Statistical test: over many iterations, the observed frequency
        should approximate the defined probability distribution.
        Uses a tolerance of 5% for each face.
        """
        probs = [0.1, 0.2, 0.3, 0.1, 0.2, 0.1]
        n = 10000
        results = generate_biased_rolls(probs, n)
        counts = [0] * 6
        for val in results:
            counts[val - 1] += 1

        for i in range(6):
            observed_freq = counts[i] / n
            expected_freq = probs[i]
            self.assertAlmostEqual(observed_freq, expected_freq, delta=0.05,
                msg=f"Face {i+1}: expected ~{expected_freq}, got {observed_freq}")

    def test_zero_probability_face_never_appears(self):
        """A face with 0 probability should never appear."""
        probs = [0.0, 0.5, 0.0, 0.5, 0.0, 0.0]
        results = generate_biased_rolls(probs, 1000)
        for val in results:
            self.assertIn(val, [2, 4])

    # --- Error handling ---

    def test_invalid_number_of_random_zero(self):
        """number_of_random = 0 should raise ValueError."""
        probs = [1/6] * 6
        with self.assertRaises(ValueError):
            generate_biased_rolls(probs, 0)

    def test_invalid_number_of_random_negative(self):
        """Negative number_of_random should raise ValueError."""
        probs = [1/6] * 6
        with self.assertRaises(ValueError):
            generate_biased_rolls(probs, -5)

    def test_invalid_number_of_random_string(self):
        """String number_of_random should raise ValueError."""
        probs = [1/6] * 6
        with self.assertRaises(ValueError):
            generate_biased_rolls(probs, "ten")


class TestProcessRequest(unittest.TestCase):
    """Tests for process_request (API logic without running the server)."""

    def test_valid_request(self):
        """Valid payload should return success with dice results."""
        payload = {
            "probabilities": [0.1, 0.2, 0.3, 0.1, 0.2, 0.1],
            "number_of_random": 10
        }
        result, status = process_request(payload)
        self.assertEqual(status, 200)
        self.assertEqual(result["status"], "success")
        self.assertEqual(len(result["dices"]), 10)
        self.assertEqual(result["probabilities"], payload["probabilities"])

    def test_missing_probabilities(self):
        """Payload without 'probabilities' should return error."""
        payload = {"number_of_random": 10}
        result, status = process_request(payload)
        self.assertEqual(status, 400)
        self.assertEqual(result["status"], "error")
        self.assertIn("probabilities", result["message"])

    def test_missing_number_of_random(self):
        """Payload without 'number_of_random' should return error."""
        payload = {"probabilities": [0.1, 0.2, 0.3, 0.1, 0.2, 0.1]}
        result, status = process_request(payload)
        self.assertEqual(status, 400)
        self.assertEqual(result["status"], "error")

    def test_invalid_payload_not_dict(self):
        """Non-dict payload should return error."""
        result, status = process_request("not a dict")
        self.assertEqual(status, 400)
        self.assertEqual(result["status"], "error")

    def test_invalid_payload_none(self):
        """None payload should return error."""
        result, status = process_request(None)
        self.assertEqual(status, 400)

    def test_invalid_probabilities_in_payload(self):
        """Invalid probabilities in payload should return 400."""
        payload = {
            "probabilities": [0.5, 0.5],  # only 2 entries
            "number_of_random": 10
        }
        result, status = process_request(payload)
        self.assertEqual(status, 400)
        self.assertIn("exactly 6", result["message"])

    def test_invalid_number_of_random_type(self):
        """Non-integer number_of_random should return 400."""
        payload = {
            "probabilities": [0.1, 0.2, 0.3, 0.1, 0.2, 0.1],
            "number_of_random": "ten"
        }
        result, status = process_request(payload)
        self.assertEqual(status, 400)

    def test_empty_payload(self):
        """Empty dict payload should return error for missing fields."""
        result, status = process_request({})
        self.assertEqual(status, 400)


if __name__ == '__main__':
    unittest.main()
